### PR TITLE
add series to metadata

### PR DESCRIPTION
**Pull request by jamesbeedy**
* added 'series' key in metadata.yaml
* specified xenial as supported series

### CODE REVIEW

**Comment by ryan-beisner** [comment]
:+1:

**Comment by freeekanayaka** [comment]
@marcoceppi what's needed to push this officially to the Juju store? There's still no xenial series there.

I've seen you've created a “Charm CI/CD team” in Launchpad, is the idea that all members of this team are/will-be able to push/plublish/promote the jenkins charm to the store?

**Comment by marcoceppi** [comment]
that's the plan, I'll get that updated in the next hour.

**Comment by dpb1** [comment]
@marcoceppi Can we get this merged please?

**Comment by marcoceppi** [comment]
It's been merged for like  2 days

**Comment by freeekanayaka** [comment]
While at it, can we also push the xenial series to stable channel of the
store?

**Comment by marcoceppi** [comment]
That I can do

**Pull request merged**
