### PR TITLE
Add support for bionic

### PR DESCRIPTION
**Pull request by mthaddon**
Still WIP. Currently failing to restart the service in the test I'm running, but it looks like jenkins does deploy at least.

### CODE REVIEW

**Comment by mthaddon** [comment]
Ok, so this still doesn't work with openjdk-11-jre-headless package installed (vs. default-jre-headless). Will need to keep looking.

**Comment by mthaddon** [comment]
Have done a test deployment with this on both xenial and bionic and confirmed Jenkins is running as expected.

**Comment by sparkiegeek** [comment]
:+1:

**Comment by 4a6f656c** [comment]
LGTM

**Pull request merged**
