### PR TITLE
Configure new nodes to use the JNLP launchers

### LINKED ISSUE #14: Amulet tests are failing.
I got some amulet tests failing: http://pastebin.ubuntu.com/23746603/

Thanks

### PR DESCRIPTION
**Pull request by freeekanayaka**
This fixes #14, a regression highlighted by the slave integration tests,
where starting from Jenkins 2.27 the slave would be rejected at
registration.

See also:

https://issues.jenkins-ci.org/browse/JENKINS-39232

### CODE REVIEW

**Comment by freeekanayaka** [comment]
If someone cares to review this fix, please go ahead or I'll just land it tomorrow (since it's a bad regression).

**Comment by freeekanayaka** [comment]
@marcoceppi thanks for approving, I've tried to push to the stable channel but I'm getting an error:

```bash
$ charm publish ~cicd/xenial/jenkins-2
ERROR cannot publish charm or bundle: unauthorized: access denied for user "free.ekanayaka"
```

I was able to publish fine to edge/development.

Not sure if there's some additional step required (pushing to the charms review queue perhaps? if so who do I do that?).

**Comment by tkuhlman** [comment]
This may be version dependent but I am finding that the launcher needs to be set to 'hudson.slaves.JNLPLauncher' like I did in PR #16, in this change it is set to 'jenkins.LAUNCHER_JNLP' which still doesn't work on my test system.

**Comment by freeekanayaka** [comment]
The 0.4.13 version python-jenkins published in pypi and pushed when building the charm does set jenkins.LAUNCHER_JNLP to "hudson.slaves.JNLPLauncher":

https://git.openstack.org/cgit/openstack/python-jenkins/tree/jenkins/__init__.py?h=0.4.13#n85

(and this should work as demonstrated by the integration test).

You might want to check that when the hooks run the actually import the correct jenkins version (which is included in the wheelhouse directory of the charm).

If that version is not 0.4.13, there might be a bug in the way virtualenvs are setup by the base layer?

**Comment by tkuhlman** [comment]
That probably explains it, I wasn't using bundletester when running this and am not sure what state my dependencies were in. I was skipping bundle tester because I was testing the storage change and that requires a version of amulet not yet available from pypi.

**Comment by marcoceppi** [comment]
@freeekanayaka that's because stable channel for charms are locked except for charmers. I'll chat with you offline about this

**Comment by freeekanayaka** [comment]
@marcoceppi I'm still waiting for that offline chat :) Note that this is a bad regression that affects the current charm in the stable channel. Anyone deploying the jenkins charm and relating a slave will hit it. If for whatever reason it's difficult to grant me the privileges to publish to the stable channel, can someone else please do it in the meantime?

**Pull request merged**
